/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************/
#include <stdint.h>
#include <stdlib.h>
#include <stdio.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

// GPIO
#define GPIO_BASE 0x40010800
#define GPIO_ODR *(volatile int*)(GPIO_BASE + 0x0C)
#define GPIO_CRH *(volatile int*)(GPIO_BASE + 0x04)
#define GPIOx_CRL *(volatile int*)(GPIO_BASE + 0x00)

//RCC
#define RCC_BASE  0x40021000
#define RCC_APB2EN *(volatile int*)(RCC_BASE + 0x18)
#define RCC_CFGR *(volatile int*)(RCC_BASE + 0x04)
#define RCC_CR *(volatile int*)(RCC_BASE)

// EXTI
#define EXTI_BASE   0x40010400
#define EXTI_IMR    *(volatile int*)(EXTI_BASE + 0x00)
#define EXTI_RTSR   *(volatile int*)(EXTI_BASE + 0x08)
#define EXTI_PR     *(volatile int*)(EXTI_BASE + 0x14)
#define NVIC_ISER0  *(volatile int*)(0xE000E100)

// AFIO
#define AFIO_BASE   0x4001000
#define AFIO_EXTICR1 *(volatile int*)(AFIO_BASE + 0x08)
void clock_init()
{
	RCC_CFGR |= 0b10<<0; 		//System clock -> switch to PLL
	RCC_CFGR |= 0b100<<8 ;		//APB1 Prescale /2
	RCC_CFGR |= 0b101<<11 ;		//APB2 Prescale /4
	RCC_CFGR |= 0b110<<18 ;		//PLL MF *8
	RCC_CR	 |=1<<24 ;			//PLL Enabled
	RCC_APB2EN |= 1<<2 ;		//Enable Clock for GPIOA
	RCC_APB2EN |= (1<<0);      // Alternate function IO clock enable
}

void GPIO_init()
{
	GPIO_CRH &=0xff0fffff;
	GPIO_CRH |=0x00200000;

	GPIOx_CRL |=1<<2 ;		//floating input
	AFIO_EXTICR1 = 0x0 ;
}

void EXTI_init(void)
{
    EXTI_IMR |= (1<<0); // Interrupt mask register enable for EXTI0
    EXTI_RTSR |= (1<<0); //  Rising trigger enabled for EXTI0
    NVIC_ISER0 |= (1<<6); // Enable NVIC IRQ 6 (EXTI0)
}
int main(void)
{
	clock_init();
	GPIO_init();
    EXTI_init();
    while(1);
}

void EXTI0_IRQHandler()
{
    // Toggle LED on pin 13
	GPIO_ODR ^= (1<<13) ;

    // Clear pending status of EXTI0
    EXTI_PR |= (1<<0);
}

